name: Bug report
description: Report a bug to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
      placeholder: Steps + expected vs actual
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide the minimal steps to reproduce the issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant output or attach screenshots.
      render: shell
    validations:
      required: false
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Web app (Next.js)
        - Convex backend
        - Auth (Clerk)
        - Analytics (PostHog)
        - CLI
        - Docs
    validations:
      required: true

